#sdk: "C:/Dev/Software/Motorola/RhoMobileSuite/2.2/ruby/lib/ruby/gems/1.9.1/gems/rhodes-3.5.1.12"
sdkversion: 3.5.0
name: star-rhodes
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.star-rhodes
  BundleURLScheme: star-rhodes
wp:
  productid: 'a57787f0-693c-0130-0525-02004c4f4f50'
symbian:
  uid: '0xebefcafc'
android:
  version: 2.1

extensions: ["json", "another-extension"]
